### ISSUE TITLE
When I call .for_each_index_value of MapView, it won't return

### ISSUE THREAD

**Issue by kikakkz** [linera-io/linera-protocol#1097]
Description:
When I call .for_each_index_value of MapView, it won't return

Steps:
1  Define MapView in state.rs
2  Call .for_each_index_value of MapView in contract.rs execute_message

Result:
.for_each_index_value won't return, and the application will be stuck

**Comment by ma2bd** [comment]
Do you have a piece of code that shows the issue? Are you using .await?

**Comment by kikakkz** [comment]
> Do you have a piece of code that shows the issue? Are you using .await?

https://github.com/web3eye-io/res-peer/blob/3db88bc301c1f73a2fb0af21fafe1dffcaef074e/review/src/contract.rs#L307 the commented code here will be stuck. due to we cannot get full history of channel currently, what i want to do here is send all reviewers to new subscriber when it subscribes

**Comment by kikakkz** [comment]
> > Do you have a piece of code that shows the issue? Are you using .await?
> 
> https://github.com/web3eye-io/res-peer/blob/3db88bc301c1f73a2fb0af21fafe1dffcaef074e/review/src/contract.rs#L307 the commented code here will be stuck. due to we cannot get full history of channel currently, what i want to do here is send all reviewers to new subscriber when it subscribes

It's OK with .indices. https://github.com/web3eye-io/res-peer/blob/d12c2fd0452c4a72dfca372266483e75a2fb9bd6/review/src/contract.rs#L411

**Comment by afck** [comment]
So to reproduce this, one would publish and create the `review` application (with those lines uncommented), and make another chain subscribe to it? And then the workers get stuck?
Does the application have any dependencies that need to be created first?

Or is there a unit test that reproduces it?
If not it would help a lot if you could list the exact steps to reproduce the issue, and push the exact code that exhibits the problem to a branch somewhere.

**Comment by kikakkz** [comment]
> So to reproduce this, one would publish and create the `review` application (with those lines uncommented), and make another chain subscribe to it? And then the workers get stuck? Does the application have any dependencies that need to be created first?
> 
> Or is there a unit test that reproduces it? If not it would help a lot if you could list the exact steps to reproduce the issue, and push the exact code that exhibits the problem to a branch somewhere.

i'll do some more test and update later, 😄. basically what i want to do is to send the content of MapView to the new subscriber in the ExecutionResult. then i stuck when call .for_each_index_value. with .indices it's ok. so firstly you need to create review application at chain 1, then you subscribe to it from another chain 2. and then the application of chain 1 stuck when it want to send its MapView to application of chain 2. but i check  .for_each_index_value and .indices, they're almost the same. i'll confirm firstly.

**Comment by kikakkz** [comment]
@ma2bd @afck i test again and i can confirm the issue is exist.
https://github.com/web3eye-io/res-peer/blob/54b16e5eab972f15f47415b78e1e94ac7f779bdb/review/src/contract.rs#L423C1-L423C1
i add code here to test: one is call .indices to get keys of MapView then get element with key, it's ok. another (commented code) is to get elements with .for_each_index_value, and it'll be stuck.

* the steps to reproduce the issue is:

1. run two chains
2. publish and create review application on chain 1, in review application we have a RequestSubscribe message to let review application of other chain to subscribe
3. request review application on chain 2
4. call RequestSubscribe operation to review application on chain 2. the RequestSubscribe operation will send a message to the creation chain of review application
5. review application on chain 1 (creation chain) will send its reviewers which were stored in MapView to the message sender (context.message_id.chain_id)

`with .indices, it'll be ok. and with .for_each_index_value, it'll stuck when call .for_each_index_value.`

i also add some log for both test code, and with .indices, log will output
```
Message subscribe review from
Subscribing review from
Sync reviewers to
Synced reviewers to
Subscribed to
```
and with .for_each_index_value, log will output part of above them stuck
```
Message subscribe review from
Subscribing review from
Sync reviewers to
```
i'll try to write some unit test code for that to easier reproduce it. and if you need i'm happy to provide more information or a remote debug, etc.

**Comment by ma2bd** [comment]
Thanks @kikakkz for the report. Much appreciated

**Comment by MathieuDutSik** [comment]
There was no test of `for_each_index_value` in the code. I added that in the test and did not detect any problem. So, it does not look like a purely `linera-views`problem.

**Comment by kikakkz** [comment]
* I add following log to for_each_index_value in map_view.rs to test (here please check line number to confirm I add to right place, and all linera executions and contract applications are recompiled after adding log)

![image](https://github.com/linera-io/linera-protocol/assets/13128505/f2958206-ccef-4a5b-b951-1b4f8d8b8c3e)

* Call for_each_index_value in contract.rs as following

![image](https://github.com/linera-io/linera-protocol/assets/13128505/0ab0454c-55e0-4fbf-9c24-e6170bd6e6a4)

* And I don't get the first line log

![image](https://github.com/linera-io/linera-protocol/assets/13128505/15c7ab13-e720-4087-8e73-9fd18d68eb5f)

Is it possible that wasm contract code find wrong invocation address of for_each_index_value ?

**Comment by afck** [comment]
OK, I think I finally managed to reproduce it, as a Wasm end-to-end test based on https://github.com/linera-io/linera-protocol/commit/a68f01eb6b05e3f81c47a23236e54dfcb7811a97: https://gist.github.com/afck/fa5446a467b90a85d4389203ae1f26fa
I had to compile res-peer in release mode, otherwise it took ages to publish the bytecode.

**Comment by afck** [comment]
I do indeed see a call to `RocksDbClientInternal::find_key_values_by_prefix` that hangs. The thread completes, but the `await` from the `spawn_blocking` never returns.

**Comment by afck** [comment]
It gets weirder:

```rust
    async fn find_key_values_by_prefix(&self, key_prefix: &[u8]) -> Result<Self::KeyValues, RocksDbContextError> {
        // …
        tracing::warn!("find_key_values_by_prefix");
        let key_values_handle = tokio::task::spawn_blocking(move || {
            tracing::warn!("find_key_values_by_prefix thread");
            // …
            tracing::warn!("find_key_values_by_prefix thread done");
            key_values
        });
        let key_values = match timeout(Duration::from_secs(5), key_values_handle).await {
            Ok(result) => result?,
            Err(elapsed) => panic!("find_key_values_by_prefix spawn_blocking fail: {}", elapsed),
        };
        tracing::warn!("find_key_values_by_prefix done");
        Ok(key_values)
    }
```

prints:

```
2023-10-12T09:14:07.257126Z  WARN handle_block_proposal{nick="Client node e476187f6ddfeb9d" chain_id="e476187f" height=23}: linera_views::rocks_db: find_key_values_by_prefix
2023-10-12T09:14:07.257269Z  WARN linera_views::rocks_db: find_key_values_by_prefix thread
2023-10-12T09:14:07.258145Z  WARN linera_views::rocks_db: find_key_values_by_prefix thread done
```

But it never panics, and never prints the last message.

**Comment by MathieuDutSik** [comment]
I merged today an upgrade of rocksDB from 0.19.0 to 0.21.0. Maybe worth a retry?
Otherwise, I would like to test it myself. Could you explain everything on how to reproduce the bug?
One of my first steps would be to see if the bug is storage-dependent.
Also useful would be writing down the full list of operations in order to rerun separately. This has helped in the past.

**Comment by afck** [comment]
# How to reproduce:

Check out [my `for_each_index_value` branch of `res-peer`](https://github.com/afck/res-peer/tree/for_each_index_value), and my [my `for_each_index_value` branch of `linera-protocol`](https://github.com/afck/linera-protocol/tree/for_each_index_value), and run:

```sh
cd res-peer
cargo build --release
cd ../linera-protocol
cargo test test_rocks_db_wasm_end_to_end_review
```

The four WARN logs I added show (at least on my machine) that the spawned thread completes, but the spawning task doesn't wake up.

**Comment by afck** [comment]
@MathieuDutSik: The above branch is rebased on current main, so it looks like the RocksDB update didn't fix it, unfortunately.

**Comment by MathieuDutSik** [comment]
Thank you for looking at that. I also obtained the blocking with `ScyllaDb`.
